# Generated by Django 3.2 on 2021-04-16 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time_created', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('seats_occupied', models.IntegerField()),
                ('location', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20)),
                ('ratings', models.CharField(max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashbus_web.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('number_of_trips', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_address', models.CharField(default='', max_length=60)),
                ('end_address', models.CharField(default='Ashesi University', max_length=60)),
                ('start_location', models.CharField(max_length=40)),
                ('end_location', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashbus_web.person')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashbus_web.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashbus_web.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_Address', models.CharField(default='', max_length=80)),
                ('pickup_location', models.CharField(max_length=60)),
                ('dropoff_Address', models.CharField(default='Ashesi University ', max_length=80)),
                ('pickup_time', models.TimeField()),
                ('dropoff_time', models.TimeField()),
                ('trip_date', models.DateField(auto_now_add=True)),
                ('payment', models.CharField(default='Pending', max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashbus_web.staff')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashbus_web.trip')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashbus_web.person'),
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashbus_web.route'),
        ),
    ]
