# Generated by Django 3.2 on 2021-04-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashbus_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
