# Generated by Django 3.2 on 2021-04-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashbus_web', '0005_auto_20210416_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_trip',
            name='dropoff_location',
            field=models.CharField(default='5.760627459528241, -0.21990174522088365', max_length=60),
        ),
    ]
