# Generated by Django 3.2 on 2021-04-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashbus_web', '0006_staff_trip_dropoff_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route',
            field=models.TextField(default='w}qa@fwc@DP@zAHPF@ZBAZ@rGClJAzLEhXCpWGfN?fI?rHC~QCvH?xIGdYEbE?rFCx\\EdSCze@GfNAD?~DAlAG?G@MJEBKBa@AqGEkE@mNE_K?cK?gDDiCXoAXuClAyE~Bg@R]DK@]FE?EBCD?@?@CHEHGLmAjAgAnAwCtDiCnDkChDs@p@cGbEq@Z}@n@HTo@Pq@ZQLyApAo@`@s@VgB\\qA`@aDjA}FlBmA\\uAV_E\\yGh@kAFc@@c@Ci@IaBQ{AUgEc@uI}@eFe@uASyDs@uD}@wGoAuFy@eCKmCYeKcA}MsAkMuAuFs@cKaAgHq@mDm@a@I}Bu@iCeAuB_A_I_EyAi@wA]gAOeAGa@Aa@?eANcCZoAPwCTaCBsOw@_DOcJA_AA_AI_AG_Dk@{Bs@}@c@oEkCwBqAeFmDoDeCaDuBkC_BsAq@sCkAgFmByIeDm@]q@i@}EoGaC_DqA{As@k@m@UmBg@kFmAsIoBkD{@gAQkCYcD[oDWcCY}Bg@eBc@aDiAuBo@iDkAWK{@g@g@_@[c@W{@KyBG_@Om@gAoBUa@kA}A[W_Ag@iAm@yAgA{GyEaCeBaAo@cCeBsA_Ao@[wBu@[IA]Cc@[kD@k@Ha@N_@j@w@V[pAeA`BgAv@Uj@GXBtBb@b@LdDfAbDlA`Cz@jAj@TRFJRz@F^z@V'),
        ),
    ]
