# Generated by Django 3.2 on 2021-04-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashbus_web', '0008_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
